import { withValidManifest } from "@coinbase/onchainkit/minikit";
import { appUrl, appDomain } from "./src/lib/env";

const ROOT = appUrl();

/**
 * The Mini App manifest, served at `/.well-known/farcaster.json`.
 *
 * `accountAssociation` proves the domain belongs to the publishing account. It
 * is generated by signing the domain with a wallet at
 * https://base.dev — paste the three fields into the env vars below rather than
 * committing them, so a fork of this repo cannot claim the same domain.
 *
 * `withValidManifest` fails the build on a malformed manifest, which is the
 * cheapest possible place to catch it: an invalid manifest does not error at
 * runtime, it just silently refuses to appear in Base App.
 */
export const minikitConfig = withValidManifest({
  accountAssociation: {
    header: process.env.FARCASTER_HEADER ?? "",
    payload: process.env.FARCASTER_PAYLOAD ?? "",
    signature: process.env.FARCASTER_SIGNATURE ?? "",
  },
  miniapp: {
    version: "1",
    name: "Slate",
    subtitle: "Baskets of tokenized stocks",
    description:
      "Build a basket of tokenized stocks on Base, buy the whole thing in one tap, and share it. Anyone can copy your slate.",
    tagline: "One tap. Whole basket.",

    homeUrl: ROOT,
    iconUrl: `${ROOT}/icon.png`,
    splashImageUrl: `${ROOT}/splash.png`,
    splashBackgroundColor: "#0a0b0d",
    heroImageUrl: `${ROOT}/hero.png`,
    webhookUrl: `${ROOT}/api/webhook`,

    ogTitle: "Slate",
    ogDescription: "Build and share baskets of tokenized stocks on Base.",
    ogImageUrl: `${ROOT}/hero.png`,

    primaryCategory: "finance",
    tags: ["stocks", "investing", "baskets", "rwa", "portfolio"],

    // Slate reads Chainlink feeds and B20 balances on Base mainnet and settles
    // in USDC there. It has nothing to show on any other chain.
    requiredChains: ["eip155:8453"],
    canonicalDomain: appDomain(),
  },
});

export type MiniKitConfig = typeof minikitConfig;
